// Provisional balancing values. Replace these with the player's final rules.
export const RULES = {
  openings: {
    founding: { label: "建国初期", treasury: 120000, affairs: 3 },
    prosperous: { label: "盛世", treasury: 300000, affairs: 1 },
    troubled: { label: "乱世", treasury: 60000, affairs: 5 },
  },
  calendar: { minutesPerDay: 1440, daysPerMonth: 30, daysPerYear: 360 },
  startMinute: 480,
  endMinute: 1320,
  income: 12000,
  upkeep: 8000,
  costs: { relief: 20000, reward: 3000, military: 25000, policy: 5000 },
  minutes: { speak: 20, summon: 45, introduce: 30, inspect: 120, investigate: 120, relief: 60, reward: 30, punish: 45, military: 90, policy: 90, travel: 120, study: 90, rest: 120, heal: 45, other: 30 },
  newCharacterAge: [18, 65],
  failedActionMinutes: 15,
  suicideMinutes: 1,
  npcInterval: 120,
  npcEventChance: 0.16,
  innateRange: { intelligence: [25, 98], force: [15, 98], loyalty: [8, 98], talent: [20, 92] },
  traits: ["谨慎", "勇敢", "贪婪", "正直", "多疑", "仁厚", "固执", "圆滑", "好奇", "直率", "野心", "务实"],
  initial: { health: [82, 100], fatigue: [0, 15], pressure: [0, 20], wealth: [1000, 10000], ambition: [20, 80], ambitious: [70, 95] },
  body: {
    healthy: 75, unwell: 50, critical: 25,
    awakeFatigue: 2, overnightFatigueRecovery: 8, overnightHealthRecovery: 0.35,
    actionFatigueMinutes: 35, fatigueDamageThreshold: 85, fatigueDamagePerTick: 1.5,
    illnessChance: 0.007, illnessFatigueFactor: 0.0001, illnessAgeFactor: 0.00008,
    illnessSeverity: [3, 8], illnessDamageFactor: 0.2, illnessRecoveryChance: 0.07,
    illnessRecovery: 1, agingStartsAt: 55, agingDamageFactor: 0.002,
    mortalityThreshold: 20, mortalityDivisor: 250,
    restFatigueRecovery: 18, restHealthRecovery: 2,
    healingTalentDivisor: 18, healingIllnessReduction: 2,
    npcRestFatigueRecovery: 10, npcRestHealthRecovery: 1,
  },
  behavior: {
    adultAge: 16, exhausted: 70, ill: 65, disloyal: 40, ambitious: 60,
    plotActionChance: 0.4, greedyActionChance: 0.55, learningChance: 0.3,
    socialChance: 0.5, npcStudyGain: 0.4, npcTrainingGain: 0.5,
    cooperationGain: 1, supportPressureRelief: 4, disputePressure: 5, disputeLoyaltyLoss: 1,
    injuryTraitChance: 0.3, summonLoyaltyGain: 1,
    rewardBaseLoyalty: 2, rewardLoyaltyDivisor: 2000, rewardLoyaltyLimit: 12,
    reliefLoyaltyGain: 3, punishLoyaltyLoss: 18, punishAmbitionGain: 8, relativesLoyaltyLoss: 3,
    studyBaseGain: 1, studyPersonalFactor: 0.5, studyTeacherFactor: 0.4,
    reportClarityHigh: 75, reportClarityLow: 45,
  },
  plotThreshold: 100,
  plots: {
    intelligenceGainDivisor: 12, talentGainDivisor: 18, gainRandom: 6,
    concealIntelligence: 0.6, concealTalent: 0.25, cautiousConcealBonus: 10,
    matureReportChance: 0.25,
    attackIntelligence: 0.45, attackTalent: 0.4, attackForce: 0.15, attackRandom: 40,
    defenseForce: 0.5, defenseLoyalty: 0.3, defenseIntelligence: 0.15, defenseBase: 20,
    defenseFatiguePenalty: 0.15, emperorDamage: 35, guardInjury: [10, 25], plotterInjury: [8, 20], pressure: 12,
  },
  investigation: {
    intelligence: 0.4, talent: 0.4, loyalty: 0.1, fatiguePenalty: 0.15,
    suspectIntelligence: 0.35, suspectTalent: 0.2, cautiousBonus: 10,
    maturityEvidence: 20, baseChance: 0.45, minChance: 0.08, maxChance: 0.92,
  },
  embezzlement: { minimumTreasury: 2000, amount: [300, 1000], maximumLoyalty: 65 },
  tasks: {
    militaryDelayDays: 2, remoteSummonDelayDays: 2, maximumWeatherDelayDays: 1,
    militaryIntelligence: 0.25, militaryForce: 0.3, militaryTalent: 0.3, militaryLoyalty: 0.15,
    fatiguePenalty: 0.2, healthPenalty: 0.15, talentSuccess: 2, talentFailure: 1,
    pressureSuccess: -5, pressureFailure: 10, fatigueCost: 12, failureInjury: [4, 12],
  },
  daily: { eventChance: 0.3, affairsLimit: 8, stormPressure: 6, borderInjury: [3, 12], fireInjury: [5, 18], crisisPressure: 8, diplomacyPressureRelief: 4 },
  limits: { inputLength: 2000, subjectLength: 240, messages: 800, visibleMessages: 200, maximumAdvanceMinutes: 100800 },
  maxToolRounds: 4,
};

// Identity and public biography only. Every innate value and personality is drawn
// by createWorld; these templates never prescribe competence or loyalty.
export const PEOPLE = [
  { id: "empress", name: "沈令仪", age: 25, role: "皇后", group: "皇室", place: "长宁宫", bio: "出身书香世家，入宫后主持内廷事务。曾与宫中女史整理典籍。" },
  { id: "heir", name: "萧承礼", age: 6, role: "皇子", group: "皇室", place: "长宁宫", bio: "皇帝与皇后之子，正在随太傅启蒙。" },
  { id: "minister", name: "顾廷章", age: 48, role: "户部尚书", group: "朝廷", place: "户部", bio: "由地方知府升任户部尚书，曾主持田赋清册与河道修整。" },
  { id: "counsellor", name: "裴知远", age: 41, role: "中书令", group: "朝廷", place: "中书省", bio: "历任中书舍人、侍郎，参与编修朝廷典章。" },
  { id: "censor", name: "陆衡", age: 35, role: "御史", group: "朝廷", place: "御史台", bio: "科举入仕，负责监察官员和巡察地方，曾上疏整顿驿站。" },
  { id: "general", name: "卫长宁", age: 39, role: "北境统帅", group: "军伍", place: "北境", bio: "从边军校尉晋升，长期驻守北境。" },
  { id: "guard", name: "秦砚", age: 29, role: "禁军统领", group: "军伍", place: "皇城", bio: "负责皇城守卫与御前护送，父亲曾在先帝朝任禁军校尉。" },
  { id: "physician", name: "温行舟", age: 56, role: "太医", group: "内廷", place: "太医院", bio: "行医三十余年，入太医院前曾在江南参与疫病救治，著有医案。" },
  { id: "steward", name: "陈德", age: 44, role: "御前总管", group: "内廷", place: "御书房", bio: "在宫中任职多年，负责御前传话、召见与起居安排。" },
  { id: "maid", name: "阿绫", age: 20, role: "宫人", group: "内廷", place: "长宁宫", bio: "负责长宁宫的日常起居，曾在宫中女史处任事。" },
  { id: "governor", name: "韩宗", age: 46, role: "江南知府", group: "地方", place: "江南", bio: "主政江南多年，负责当地钱粮、河道与治安，最近呈报了汛情。" },
  { id: "envoy", name: "苏望舒", age: 32, role: "礼部侍郎", group: "朝廷", place: "礼部", bio: "曾出使邻国，参与互市条约与使节接待。" },
];

export const AFFAIRS = [
  { title: "江南汛情", text: "江南连雨，韩宗上疏请求检查河堤，并备粮救济。", actors: ["minister", "governor"], kind: "民生" },
  { title: "北境粮饷", text: "卫长宁来信，边军粮饷需补充，驻防轮换也等待安排。", actors: ["general"], kind: "军事" },
  { title: "驿站失修", text: "陆衡巡察发现数处驿站失修，文书送达比往常迟缓。", actors: ["censor"], kind: "朝政" },
  { title: "使节来访", text: "邻国使节抵京，苏望舒请示接见与互市事宜。", actors: ["envoy"], kind: "外交" },
  { title: "京郊米价", text: "京郊商贾报告米价上涨，户部正在查验仓储与运输。", actors: ["minister"], kind: "财政" },
];
